[package]
name = "LemoGUI"
version = "0.0.1-nightly"
authors = ["eaglekindoms <huyongmao35@outlook.com>"]
edition = "2018"
description = "GUI library dependent on wgpu"
license = "MIT"
keywords = ["graphics", "gui"]
repository = "https://github.com/eaglekindoms/LemoGUI"

[[example]]
name = "show_button"
path = "example/show_button.rs"

[[example]]
name = "test_font"
path = "example/test_font.rs"

[[example]]
name = "show_shap"
path = "example/show_shape.rs"

[[example]]
name = "test_graph_algo"
path = "example/proto/test_algo.rs"

[dependencies]
wgpu = "0.9.0"
async-trait = "0.1.51"
winit = "0.24.0"
futures = "0.3.10"
cgmath = "0.17"
log = "0.4.14"
simple_logger = "1.11.0"
rand = "0.8.2"
bytemuck = { version = "1.4", features = ["derive"] }
image = "0.23.12"
ab_glyph = "0.2.11"

[build-dependencies]
shaderc = "0.7.0"
anyhow = "1.0"
fs_extra = "1.1"
glob = "0.3"