[package]
name = "LemoGUI"
version = "0.0.1"
authors = ["eaglekindoms <huyongmao35@outlook.com>"]
edition = "2018"

[[example]]
name = "show_button"
path = "example/show_button.rs"

[[example]]
name = "test_font"
path = "example/test_font.rs"

[[example]]
name = "show_shap"
path = "example/show_shape.rs"

[[example]]
name = "test_graph_algo"
path = "example/test_graph_algo.rs"

[dependencies]
wgpu = "0.9.0"
async-trait = "*"
winit = "0.24.0"
futures = "0.3.10"
cgmath = "0.17"
log = "*"
simple_logger = "1.11.0"
rand = "0.8.2"
bytemuck = { version = "1.4", features = ["derive"] }
image = "0.23.12"
ab_glyph = "0.2.9"

font-kit = "0.10.0"
pathfinder_geometry = "0.5"

[build-dependencies]
shaderc = "0.7.0"
anyhow = "1.0"
fs_extra = "1.1"
glob = "0.3"