use sdl2::event::Event;
use sdl2::keyboard::Keycode;
use sdl2::mouse::MouseButton;

use crate::event::*;

/// sdl2鼠标按键转换
impl From<sdl2::mouse::MouseButton> for Mouse {
    fn from(mouse_btn: MouseButton) -> Self {
        match mouse_btn {
            MouseButton::Unknown => Mouse::Other,
            MouseButton::Left => Mouse::Left,
            MouseButton::Middle => Mouse::Middle,
            MouseButton::Right => Mouse::Right,
            MouseButton::X1 => Mouse::Other,
            MouseButton::X2 => Mouse::Other,
        }
    }
}

/// sdl2事件转换
impl From<sdl2::event::Event> for GEvent {
    fn from(sdl2_event: Event) -> Self {
        match sdl2_event {
            Event::KeyDown { keycode, .. } => {
                let mut key_code = None;
                if let Some(key) = keycode {
                    key_code = Some(translate_key(key))
                };
                GEvent {
                    event: EventType::KeyBoard(key_code),
                    state: State::Pressed,
                }
            }
            Event::KeyUp { keycode, .. } => {
                let mut key_code = None;
                if let Some(key) = keycode {
                    key_code = Some(translate_key(key))
                };
                GEvent {
                    event: EventType::KeyBoard(key_code),
                    state: State::Released,
                }
            }
            Event::MouseButtonDown { mouse_btn, .. } => GEvent {
                event: EventType::Mouse(mouse_btn.into()),
                state: State::Pressed,
            },
            Event::MouseButtonUp { mouse_btn, .. } => GEvent {
                event: EventType::Mouse(mouse_btn.into()),
                state: State::Released,
            },
            _ => GEvent {
                event: EventType::Other,
                state: State::None,
            },
        }
    }
}

/// 键盘按键类型转换
pub(crate) fn translate_key(key: Keycode) -> KeyCode {
    match key {
        Keycode::Num0 => KeyCode::Numpad0,
        Keycode::Num1 => KeyCode::Numpad1,
        Keycode::Num2 => KeyCode::Numpad2,
        Keycode::Num3 => KeyCode::Numpad3,
        Keycode::Num4 => KeyCode::Numpad4,
        Keycode::Num5 => KeyCode::Numpad5,
        Keycode::Num6 => KeyCode::Numpad6,
        Keycode::Num7 => KeyCode::Numpad7,
        Keycode::Num8 => KeyCode::Numpad8,
        Keycode::Num9 => KeyCode::Numpad9,

        Keycode::A => KeyCode::A,
        Keycode::B => KeyCode::B,
        Keycode::C => KeyCode::C,
        Keycode::D => KeyCode::D,
        Keycode::E => KeyCode::E,
        Keycode::F => KeyCode::F,
        Keycode::G => KeyCode::G,
        Keycode::H => KeyCode::H,
        Keycode::I => KeyCode::I,
        Keycode::J => KeyCode::J,
        Keycode::K => KeyCode::K,
        Keycode::L => KeyCode::L,
        Keycode::M => KeyCode::M,
        Keycode::N => KeyCode::N,
        Keycode::O => KeyCode::O,
        Keycode::P => KeyCode::P,
        Keycode::Q => KeyCode::Q,
        Keycode::R => KeyCode::R,
        Keycode::S => KeyCode::S,
        Keycode::T => KeyCode::T,
        Keycode::U => KeyCode::U,
        Keycode::V => KeyCode::V,
        Keycode::W => KeyCode::W,
        Keycode::X => KeyCode::X,
        Keycode::Y => KeyCode::Y,
        Keycode::Z => KeyCode::Z,

        Keycode::Escape => KeyCode::Escape,
        Keycode::F1 => KeyCode::F1,
        Keycode::F2 => KeyCode::F2,
        Keycode::F3 => KeyCode::F3,
        Keycode::F4 => KeyCode::F4,
        Keycode::F5 => KeyCode::F5,
        Keycode::F6 => KeyCode::F6,
        Keycode::F7 => KeyCode::F7,
        Keycode::F8 => KeyCode::F8,
        Keycode::F9 => KeyCode::F9,
        Keycode::F10 => KeyCode::F10,
        Keycode::F11 => KeyCode::F11,
        Keycode::F12 => KeyCode::F12,
        Keycode::F13 => KeyCode::F13,
        Keycode::F14 => KeyCode::F14,
        Keycode::F15 => KeyCode::F15,
        Keycode::F16 => KeyCode::F16,
        Keycode::F17 => KeyCode::F17,
        Keycode::F18 => KeyCode::F18,
        Keycode::F19 => KeyCode::F19,
        Keycode::F20 => KeyCode::F20,
        Keycode::F21 => KeyCode::F21,
        Keycode::F22 => KeyCode::F22,
        Keycode::F23 => KeyCode::F23,
        Keycode::F24 => KeyCode::F24,

        Keycode::PrintScreen => KeyCode::Snapshot,
        Keycode::ScrollLock => KeyCode::Scroll,
        Keycode::Pause => KeyCode::Pause,
        Keycode::Insert => KeyCode::Insert,
        Keycode::Home => KeyCode::Home,
        Keycode::Delete => KeyCode::Delete,
        Keycode::End => KeyCode::End,
        Keycode::PageDown => KeyCode::PageDown,
        Keycode::PageUp => KeyCode::PageUp,
        Keycode::Left => KeyCode::Left,
        Keycode::Up => KeyCode::Up,
        Keycode::Right => KeyCode::Right,
        Keycode::Down => KeyCode::Down,
        Keycode::Backspace => KeyCode::Backspace,
        Keycode::Return => KeyCode::Return,
        Keycode::Space => KeyCode::Space,

        Keycode::NumLockClear => KeyCode::Numlock,
        Keycode::Kp0 => KeyCode::Numpad0,
        Keycode::Kp1 => KeyCode::Numpad1,
        Keycode::Kp2 => KeyCode::Numpad2,
        Keycode::Kp3 => KeyCode::Numpad3,
        Keycode::Kp4 => KeyCode::Numpad4,
        Keycode::Kp5 => KeyCode::Numpad5,
        Keycode::Kp6 => KeyCode::Numpad6,
        Keycode::Kp7 => KeyCode::Numpad7,
        Keycode::Kp8 => KeyCode::Numpad8,
        Keycode::Kp9 => KeyCode::Numpad9,

        Keycode::KpPlus => KeyCode::NumpadAdd,
        Keycode::KpMinus => KeyCode::NumpadSubtract,
        Keycode::KpMultiply => KeyCode::NumpadMultiply,
        Keycode::KpDivide => KeyCode::NumpadDivide,
        Keycode::KpDecimal => KeyCode::NumpadDecimal,
        Keycode::KpComma => KeyCode::NumpadComma,
        Keycode::KpEnter => KeyCode::NumpadEnter,
        Keycode::KpEquals => KeyCode::NumpadEquals,

        Keycode::Copy => KeyCode::Copy,
        Keycode::Paste => KeyCode::Paste,
        Keycode::Cut => KeyCode::Cut,

        Keycode::At => KeyCode::At,
        Keycode::Caret => KeyCode::Caret,
        Keycode::Equals => KeyCode::Equals,
        Keycode::Plus => KeyCode::Plus,
        Keycode::Power => KeyCode::Power,
        Keycode::Asterisk => KeyCode::Asterisk,
        Keycode::Semicolon => KeyCode::Semicolon,
        Keycode::Backslash => KeyCode::Backslash,
        Keycode::Colon => KeyCode::Colon,
        Keycode::Comma => KeyCode::Comma,
        Keycode::Calculator => KeyCode::Calculator,
        Keycode::Underscore => KeyCode::Underline,
        Keycode::Period => KeyCode::Period,

        Keycode::Tab => KeyCode::Tab,
        Keycode::LAlt => KeyCode::LAlt,
        Keycode::RAlt => KeyCode::RAlt,
        Keycode::LeftBracket => KeyCode::LBracket,
        Keycode::RightBracket => KeyCode::RBracket,
        Keycode::LShift => KeyCode::LShift,
        Keycode::RShift => KeyCode::RShift,
        Keycode::VolumeDown => KeyCode::VolumeDown,
        Keycode::VolumeUp => KeyCode::VolumeUp,

        Keycode::Mail => KeyCode::Mail,
        Keycode::MediaSelect => KeyCode::MediaSelect,
        Keycode::Minus => KeyCode::Minus,
        Keycode::Mute => KeyCode::Mute,
        Keycode::Slash => KeyCode::Slash,
        Keycode::Sleep => KeyCode::Sleep,
        Keycode::Stop => KeyCode::Stop,

        Keycode::Exclaim => KeyCode::Exclaim,
        Keycode::Quotedbl => KeyCode::Quotedbl,
        Keycode::Hash => KeyCode::Hash,
        Keycode::Dollar => KeyCode::Dollar,
        Keycode::Percent => KeyCode::Percent,
        Keycode::Ampersand => KeyCode::Ampersand,
        Keycode::Quote => KeyCode::Quote,
        Keycode::LeftParen => KeyCode::LeftParen,
        Keycode::RightParen => KeyCode::RightParen,
        Keycode::Less => KeyCode::Less,
        Keycode::Greater => KeyCode::Greater,
        Keycode::Question => KeyCode::Question,
        Keycode::Backquote => KeyCode::Backquote,
        Keycode::CapsLock => KeyCode::CapsLock,
        Keycode::KpPeriod => KeyCode::Period,
        Keycode::Application => KeyCode::Application,
        Keycode::Execute => KeyCode::Execute,
        Keycode::Help => KeyCode::Help,
        Keycode::Menu => KeyCode::Menu,
        Keycode::Select => KeyCode::Select,
        Keycode::Again => KeyCode::Again,
        Keycode::Undo => KeyCode::Undo,
        Keycode::Find => KeyCode::Find,
        Keycode::KpEqualsAS400 => KeyCode::KpEqualsAS400,
        Keycode::AltErase => KeyCode::AltErase,
        Keycode::Sysreq => KeyCode::Sysreq,
        Keycode::Cancel => KeyCode::Cancel,
        Keycode::Clear => KeyCode::Clear,
        Keycode::Prior => KeyCode::Period,
        Keycode::Return2 => KeyCode::Return2,
        Keycode::Separator => KeyCode::Separator,
        Keycode::Out => KeyCode::Out,
        Keycode::Oper => KeyCode::Oper,
        Keycode::ClearAgain => KeyCode::ClearAgain,
        Keycode::CrSel => KeyCode::CrSel,
        Keycode::ExSel => KeyCode::ExSel,
        Keycode::Kp00 => KeyCode::Kp00,
        Keycode::Kp000 => KeyCode::Kp000,
        Keycode::ThousandsSeparator => KeyCode::ThousandsSeparator,
        Keycode::DecimalSeparator => KeyCode::DecimalSeparator,
        Keycode::CurrencyUnit => KeyCode::CurrencyUnit,
        Keycode::CurrencySubUnit => KeyCode::CurrencySubUnit,
        Keycode::KpLeftParen => KeyCode::KpLeftParen,
        Keycode::KpRightParen => KeyCode::KpRightParen,
        Keycode::KpLeftBrace => KeyCode::KpLeftBrace,
        Keycode::KpRightBrace => KeyCode::KpRightBrace,
        Keycode::KpTab => KeyCode::Tab,
        Keycode::KpBackspace => KeyCode::Backspace,
        Keycode::KpA => KeyCode::KpA,
        Keycode::KpB => KeyCode::KpB,
        Keycode::KpC => KeyCode::KpC,
        Keycode::KpD => KeyCode::KpD,
        Keycode::KpE => KeyCode::KpE,
        Keycode::KpF => KeyCode::KpF,
        Keycode::KpXor => KeyCode::KpXor,
        Keycode::KpPower => KeyCode::KpPower,
        Keycode::KpPercent => KeyCode::Percent,
        Keycode::KpLess => KeyCode::Less,
        Keycode::KpGreater => KeyCode::Greater,
        Keycode::KpAmpersand => KeyCode::Ampersand,
        Keycode::KpDblAmpersand => KeyCode::KpDblAmpersand,
        Keycode::KpVerticalBar => KeyCode::KpVerticalBar,
        Keycode::KpDblVerticalBar => KeyCode::KpDblVerticalBar,
        Keycode::KpColon => KeyCode::Colon,
        Keycode::KpHash => KeyCode::Hash,
        Keycode::KpSpace => KeyCode::Space,
        Keycode::KpAt => KeyCode::At,
        Keycode::KpExclam => KeyCode::Exclaim,
        Keycode::KpMemStore => KeyCode::KpMemStore,
        Keycode::KpMemRecall => KeyCode::KpMemRecall,
        Keycode::KpMemClear => KeyCode::KpMemClear,
        Keycode::KpMemAdd => KeyCode::KpMemAdd,
        Keycode::KpMemSubtract => KeyCode::KpMemSubtract,
        Keycode::KpMemMultiply => KeyCode::KpMemMultiply,
        Keycode::KpMemDivide => KeyCode::KpMemDivide,
        Keycode::KpPlusMinus => KeyCode::KpPlusMinus,
        Keycode::KpClear => KeyCode::Clear,
        Keycode::KpClearEntry => KeyCode::KpClearEntry,
        Keycode::KpBinary => KeyCode::KpBinary,
        Keycode::KpOctal => KeyCode::KpOctal,
        Keycode::KpHexadecimal => KeyCode::KpHexadecimal,
        Keycode::LCtrl => KeyCode::LControl,
        Keycode::LGui => KeyCode::LGui,
        Keycode::RCtrl => KeyCode::RControl,
        Keycode::RGui => KeyCode::RGui,
        Keycode::Mode => KeyCode::Mode,
        Keycode::AudioNext => KeyCode::AudioNext,
        Keycode::AudioPrev => KeyCode::AudioPrev,
        Keycode::AudioStop => KeyCode::AudioStop,
        Keycode::AudioPlay => KeyCode::AudioPlay,
        Keycode::AudioMute => KeyCode::AudioMute,
        Keycode::Www => KeyCode::Www,
        Keycode::Computer => KeyCode::Computer,
        Keycode::AcSearch => KeyCode::AcSearch,
        Keycode::AcHome => KeyCode::AcHome,
        Keycode::AcBack => KeyCode::AcBack,
        Keycode::AcForward => KeyCode::AcForward,
        Keycode::AcStop => KeyCode::AcStop,
        Keycode::AcRefresh => KeyCode::AcRefresh,
        Keycode::AcBookmarks => KeyCode::AcBookmarks,
        Keycode::BrightnessDown => KeyCode::BrightnessDown,
        Keycode::BrightnessUp => KeyCode::BrightnessUp,
        Keycode::DisplaySwitch => KeyCode::DisplaySwitch,
        Keycode::KbdIllumToggle => KeyCode::KbdIllumToggle,
        Keycode::KbdIllumDown => KeyCode::KbdIllumDown,
        Keycode::KbdIllumUp => KeyCode::KbdIllumUp,
        Keycode::Eject => KeyCode::Eject,
    }
}
